import { cleanQuery, scanDexscreener } from "../_shared/dexscreener.js";

export async function onRequest({ request }) {
  if (request.method === "OPTIONS") {
    return withCors(new Response(null, { status: 204 }));
  }

  if (!["GET", "POST"].includes(request.method)) {
    return json({ error: "Method not allowed" }, 405);
  }

  try {
    const input = await readRedFlagRequest(request);
    if (!input.query) {
      return json({ error: "Missing red flags query", message: "Use ?q=ONDO or POST { q: 'ONDO' }" }, 400);
    }

    const report = await scanDexscreener(input.query);
    const payload = redFlagPayload(report, input.query);
    return redFlagResponse(payload, input.format, request);
  } catch (error) {
    return json(
      {
        error: "Red flags failed",
        message: error instanceof Error ? error.message : "Unknown error",
      },
      502,
    );
  }
}

async function readRedFlagRequest(request) {
  if (request.method === "GET") {
    const url = new URL(request.url);
    return {
      query: cleanRedFlagQuery(
        url.searchParams.get("q") ||
          url.searchParams.get("query") ||
          url.searchParams.get("asset") ||
          url.searchParams.get("token") ||
          url.searchParams.get("issuer"),
      ),
      format: cleanFormat(url.searchParams.get("format")),
    };
  }

  const body = await request.json().catch(() => ({}));
  return {
    query: cleanRedFlagQuery(body.q || body.query || body.asset || body.token || body.contract || body.issuer),
    format: cleanFormat(body.format),
  };
}

function redFlagPayload(report, query) {
  return {
    kind: "redflags",
    query,
    id: report.id,
    label: report.label,
    title: report.title,
    chain: report.chain,
    risk: report.risk,
    verdict: report.verdict,
    source: report.source,
    updatedAt: report.updatedAt,
    count: Array.isArray(report.redFlags) ? report.redFlags.length : 0,
    redFlags: Array.isArray(report.redFlags) ? report.redFlags : [],
    confidence: report.confidence,
    links: report.links,
    numbers: report.numbers,
    report,
  };
}

function redFlagMarkdown(payload) {
  const rows = payload.redFlags.length
    ? payload.redFlags
        .map((item) => {
          const action = item.action ? `\n  - Action: ${markdownText(item.action)}` : "";
          return `- ${markdownText(item.tone || "mid")}: ${markdownText(item.label || "Red flag")} - ${markdownText(item.detail || "")}${action}`;
        })
        .join("\n")
    : "- No structured red flags were returned by this scan.";

  return [
    `# DYOR Red Flags: ${markdownText(payload.title || payload.label)}`,
    [
      `- RWA asset: ${markdownText(payload.label)}`,
      `- Chain: ${markdownText(payload.chain)}`,
      `- Risk score: ${markdownText(payload.risk)}`,
      `- Verdict: ${markdownText(payload.verdict)}`,
      payload.source ? `- Source: ${markdownText(payload.source)}` : "",
      payload.updatedAt ? `- Updated: ${markdownText(payload.updatedAt)}` : "",
    ]
      .filter(Boolean)
      .join("\n"),
    `## Red Flags\n${rows}`,
    "Not financial advice or yield guarantee. Generated by dyor.sh.",
  ].join("\n\n") + "\n";
}

function redFlagResponse(payload, format, request) {
  const accept = request.headers.get("accept") || "";
  if (format === "md" || format === "markdown" || accept.includes("text/markdown")) {
    return withCors(
      new Response(redFlagMarkdown(payload), {
        headers: {
          "content-type": "text/markdown; charset=utf-8",
          "cache-control": "public, max-age=30",
        },
      }),
    );
  }

  return json(payload);
}

function cleanRedFlagQuery(value) {
  return cleanQuery(value)
    .replace(/^(?:dyor\s+)?\/?redflags?\s+/i, "")
    .replace(/^(?:dyor\s+)?\/?scan\s+/i, "")
    .replace(/^(?:dyor\s+)?\/?watch\s+/i, "")
    .replace(/^\$+/, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 500);
}

function cleanFormat(value) {
  const format = String(value || "").toLowerCase();
  return ["json", "md", "markdown"].includes(format) ? format : "";
}

function markdownText(value) {
  return String(value ?? "")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/[\\`*_{}[\]()#+.!|>-]/g, "\\$&");
}

function json(payload, status = 200) {
  return withCors(
    Response.json(payload, {
      status,
      headers: {
        "cache-control": status === 200 ? "public, max-age=30" : "no-store",
      },
    }),
  );
}

function withCors(response) {
  const headers = new Headers(response.headers);
  headers.set("access-control-allow-origin", "*");
  headers.set("access-control-allow-methods", "GET, POST, OPTIONS");
  headers.set("access-control-allow-headers", "content-type");
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}
