export function reportToMarkdown(report) {
  const parts = [
    `# DYOR Report: ${markdownText(report.title || report.label)}`,
    [
      `- Token: ${markdownText(report.label)}`,
      `- Chain: ${markdownText(report.chain)}`,
      `- Risk score: ${markdownText(report.risk)}`,
      `- Verdict: ${markdownText(report.verdict)}`,
      report.source ? `- Source: ${markdownText(report.source)}` : "",
      report.updatedAt ? `- Updated: ${markdownText(report.updatedAt)}` : "",
    ]
      .filter(Boolean)
      .join("\n"),
    `## Metrics\n${objectRows(report.metrics)}`,
  ];

  const redFlags = redFlagRows(report.redFlags);
  if (redFlags) parts.push(`## Red Flags\n${redFlags}`);

  const evidence = evidenceRows(report.evidence);
  if (evidence) parts.push(`## Evidence\n${evidence}`);

  const confidence = confidenceRows(report.confidence);
  if (confidence) parts.push(`## Research Quality\n${confidence}`);

  const watch = watchRows(report.watch);
  if (watch) parts.push(`## Watch Triggers\n${watch}`);

  const findings = findingRows(report.findings);
  if (findings) parts.push(`## Findings\n${findings}`);

  const links = sourceLinks(report);
  if (links) parts.push(`## Sources\n${links}`);

  parts.push("Not financial advice. Generated by dyor.sh.");
  return `${parts.filter(Boolean).join("\n\n")}\n`;
}

export function comparisonToMarkdown(comparison) {
  const deltas = Array.isArray(comparison.deltas)
    ? comparison.deltas
        .map(
          (item) =>
            `- ${markdownText(item.label)}: ${markdownText(comparison.left.label)} ${markdownText(item.left)} / ${markdownText(comparison.right.label)} ${markdownText(item.right)} - edge: ${markdownText(deltaLeaderLabel(item, comparison))}`,
        )
        .join("\n")
    : "";
  const findings = findingRows(comparison.findings);

  const parts = [
    `# DYOR Compare: ${markdownText(comparison.title || comparison.label)}`,
    [
      `- Verdict: ${markdownText(comparison.verdict)}`,
      `- Summary: ${markdownText(comparison.summary)}`,
      comparison.source ? `- Source: ${markdownText(comparison.source)}` : "",
      comparison.updatedAt ? `- Updated: ${markdownText(comparison.updatedAt)}` : "",
    ]
      .filter(Boolean)
      .join("\n"),
    [
      "## Scores",
      `- ${markdownText(comparison.left.label)}: ${markdownText(comparison.scores?.left ?? "")}`,
      `- ${markdownText(comparison.right.label)}: ${markdownText(comparison.scores?.right ?? "")}`,
      `- Leader: ${markdownText(comparison.scores?.leader === "left" ? comparison.left.label : comparison.scores?.leader === "right" ? comparison.right.label : "Even")}`,
    ].join("\n"),
  ];

  if (deltas) parts.push(`## Deltas\n${deltas}`);
  if (findings) parts.push(`## Findings\n${findings}`);
  parts.push(assetSnapshot(comparison.left));
  parts.push(assetSnapshot(comparison.right));
  parts.push("Not financial advice. Generated by dyor.sh.");
  return `${parts.filter(Boolean).join("\n\n")}\n`;
}

function assetSnapshot(report) {
  return [
    `## ${markdownText(report.label)} Snapshot`,
    `- Chain: ${markdownText(report.chain)}`,
    `- Risk score: ${markdownText(report.risk)}`,
    `- Verdict: ${markdownText(report.verdict)}`,
    `- Liquidity: ${markdownText(money(report.numbers?.liquidityUsd))}`,
    `- Confidence: ${markdownText(report.confidence?.score ?? report.numbers?.confidenceScore ?? "?")}`,
    redFlagRows(report.redFlags) ? `### Red Flags\n${redFlagRows(report.redFlags)}` : "",
    sourceLinks(report, 4) ? `### Sources\n${sourceLinks(report, 4)}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

function objectRows(value = {}) {
  const rows = Object.entries(value || {})
    .map(([label, item]) => `- ${markdownText(label)}: ${markdownText(item)}`)
    .join("\n");
  return rows || "- No metrics reported";
}

function evidenceRows(evidence) {
  if (!evidence || typeof evidence !== "object") return "";
  const groups = [
    ["Identity", evidence.identity],
    ["Market", evidence.market],
  ];

  return groups
    .filter(([, rows]) => Array.isArray(rows) && rows.length)
    .map(([title, rows]) => {
      const body = rows.map(([label, value]) => `- ${markdownText(label)}: ${markdownText(value)}`).join("\n");
      return `### ${markdownText(title)}\n${body}`;
    })
    .join("\n\n");
}

function redFlagRows(redFlags) {
  if (!Array.isArray(redFlags) || !redFlags.length) return "";
  return redFlags
    .map((item) => {
      const action = item.action ? ` Action: ${markdownText(item.action)}` : "";
      return `- ${markdownText(item.tone || "mid")}: ${markdownText(item.label || "Red flag")} - ${markdownText(item.detail || "")}${action}`;
    })
    .join("\n");
}

function confidenceRows(confidence) {
  if (!confidence || typeof confidence !== "object") return "";
  const reasons = Array.isArray(confidence.reasons)
    ? confidence.reasons.map((reason) => `- ${markdownText(reason)}`).join("\n")
    : "";
  return [
    `- Confidence: ${markdownText(confidence.score ?? "?")} / 100`,
    `- Label: ${markdownText(confidence.label || "Identity confidence")}`,
    `- Summary: ${markdownText(confidence.summary || "")}`,
    reasons ? `### Confidence Reasons\n${reasons}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

function watchRows(watch) {
  if (!Array.isArray(watch) || !watch.length) return "";
  return watch
    .map((item) => {
      const value = item.value ? ` (${markdownText(item.value)})` : "";
      return `- ${markdownText(item.label || "Trigger")}${value}: ${markdownText(item.detail || "")}`;
    })
    .join("\n");
}

function findingRows(findings) {
  if (!Array.isArray(findings) || !findings.length) return "";
  return findings
    .map(([tone, text]) => `- ${markdownText(tone || "note")}: ${markdownText(text)}`)
    .join("\n");
}

function sourceLinks(report, limit = 8) {
  const evidenceLinks = Array.isArray(report.evidence?.links) ? report.evidence.links : [];
  const rawLinks = [
    ...evidenceLinks.map((item) => ({ label: item.label, url: item.url })),
    ...Object.entries(report.links || {}).map(([label, url]) => ({ label: labelize(label), url })),
  ];
  const seen = new Set();

  return rawLinks
    .map((link) => ({ label: link.label, url: safeUrl(link.url) }))
    .filter((link) => {
      if (!link.url || seen.has(link.url)) return false;
      seen.add(link.url);
      return true;
    })
    .slice(0, limit)
    .map((link) => `- ${markdownLink(link.label, link.url)}`)
    .join("\n");
}

function deltaLeaderLabel(item, comparison) {
  if (item.leader === "left") return comparison.left.label;
  if (item.leader === "right") return comparison.right.label;
  return item.bias === "context" ? "Context" : "Even";
}

function markdownText(value) {
  return plainText(value).replace(/[\\`*_{}[\]()#+.!|>-]/g, "\\$&");
}

function plainText(value) {
  return String(value ?? "").replace(/\s+/g, " ").trim();
}

function markdownLink(label, url) {
  const cleanUrl = safeUrl(url).replace(/[)\s]/g, encodeURIComponent);
  return cleanUrl ? `[${markdownText(label)}](${cleanUrl})` : markdownText(label);
}

function safeUrl(value) {
  try {
    const url = new URL(String(value || ""));
    return ["http:", "https:"].includes(url.protocol) ? url.toString() : "";
  } catch {
    return "";
  }
}

function labelize(value) {
  const labels = {
    baseToken: "Base token",
    dexscreener: "Dexscreener",
    docs: "Docs",
    explorer: "Explorer",
    pairExplorer: "Pair Explorer",
    x: "X",
  };
  return (
    labels[value] ||
    String(value || "")
      .replace(/[-_]+/g, " ")
      .replace(/([a-z])([A-Z])/g, "$1 $2")
      .replace(/\b\w/g, (letter) => letter.toUpperCase())
  );
}

function money(value) {
  const amount = number(value);
  if (!amount) return "$0";
  return `$${Intl.NumberFormat("en-US", {
    notation: "compact",
    maximumFractionDigits: amount < 10_000 ? 2 : 1,
  }).format(amount)}`;
}

function number(value) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}
